name        = "dev/gitignore-cplusplus"
description = "Append gitignore rules for C++"
params      = []
requires    = []

[[file]]
src  = "files/C++.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
