name        = "dev/gitignore-phalcon"
description = "Append gitignore rules for Phalcon"
params      = []
requires    = []

[[file]]
src  = "files/Phalcon.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
