name        = "dev/gitignore-yeoman"
description = "Append gitignore rules for Yeoman"
params      = []
requires    = []

[[file]]
src  = "files/Yeoman.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
