name        = "dev/gitignore-lua"
description = "Append gitignore rules for Lua"
params      = []
requires    = []

[[file]]
src  = "files/Lua.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
