name        = "dev/gitignore-dreamweaver"
description = "Append gitignore rules for Dreamweaver"
params      = []
requires    = []

[[file]]
src  = "files/Dreamweaver.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
