name        = "dev/gitignore-kohana"
description = "Append gitignore rules for Kohana"
params      = []
requires    = []

[[file]]
src  = "files/Kohana.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
