name        = "dev/gitignore-ballerina"
description = "Append gitignore rules for Ballerina"
params      = []
requires    = []

[[file]]
src  = "files/Ballerina.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
