name        = "dev/gitignore-redcar"
description = "Append gitignore rules for Redcar"
params      = []
requires    = []

[[file]]
src  = "files/Redcar.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
