name        = "dev/gitignore-deno"
description = "Append gitignore rules for Deno"
params      = []
requires    = []

[[file]]
src  = "files/Deno.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
