name        = "dev/gitignore-webmethods"
description = "Append gitignore rules for WebMethods"
params      = []
requires    = []

[[file]]
src  = "files/WebMethods.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
