name        = "dev/gitignore-ocaml"
description = "Append gitignore rules for OCaml"
params      = []
requires    = []

[[file]]
src  = "files/OCaml.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
