name        = "dev/gitignore-d"
description = "Append gitignore rules for D"
params      = []
requires    = []

[[file]]
src  = "files/D.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
