name        = "dev/gitignore-linux"
description = "Append gitignore rules for Linux"
params      = []
requires    = []

[[file]]
src  = "files/Linux.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
