name        = "dev/gitignore-emacs"
description = "Append gitignore rules for Emacs"
params      = []
requires    = []

[[file]]
src  = "files/Emacs.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
