name        = "dev/gitignore-vvvv"
description = "Append gitignore rules for VVVV"
params      = []
requires    = []

[[file]]
src  = "files/VVVV.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
