name        = "dev/gitignore-kicad"
description = "Append gitignore rules for KiCad"
params      = []
requires    = []

[[file]]
src  = "files/KiCad.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
