name        = "dev/gitignore-packer"
description = "Append gitignore rules for Packer"
params      = []
requires    = []

[[file]]
src  = "files/Packer.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
