name        = "dev/gitignore-mercury"
description = "Append gitignore rules for Mercury"
params      = []
requires    = []

[[file]]
src  = "files/Mercury.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
