name        = "dev/gitignore-r"
description = "Append gitignore rules for R"
params      = []
requires    = []

[[file]]
src  = "files/R.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
