name        = "dev/gitignore-sugarcrm"
description = "Append gitignore rules for SugarCRM"
params      = []
requires    = []

[[file]]
src  = "files/SugarCRM.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
