name        = "dev/gitignore-codeigniter"
description = "Append gitignore rules for CodeIgniter"
params      = []
requires    = []

[[file]]
src  = "files/CodeIgniter.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
