name        = "dev/gitignore-ada"
description = "Append gitignore rules for Ada"
params      = []
requires    = []

[[file]]
src  = "files/Ada.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
