name        = "dev/gitignore-luau"
description = "Append gitignore rules for Luau"
params      = []
requires    = []

[[file]]
src  = "files/Luau.gitignore"
dest = ".gitignore"
mode = "append"   # create | append | region
